# ©  2015-2021 Deltatech
#              Dorin Hongu <dhongu(@)gmail(.)com
# See README.rst file on addons root folder for license details

from odoo import fields, models

# Effect of the accounting entry generated by each Romanian move type on the
# move's own valuation account (`l10n_ro_account_id`) and, for the moves that
# post a second stock leg, on the transfer account
# (`l10n_ro_transfer_account_id`).
#
# Derived from `stock.move._get_l10n_ro_move_type_account_list()` in
# l10n_ro_stock_account, whose tuples are
# (debit_account_key, credit_account_key, price_type, sign): a move type that
# debits `stock_valuation` adds to the valuation account, one that credits it
# subtracts.  Up to 18.0 this sign was carried by `stock.valuation.layer.value`
# itself; in 19.0 `stock.move.value` is always positive and the direction lives
# in the move type, so the check has to rebuild it.
VALUATION_SIGN = {
    "reception": 1,
    "reception_return": -1,
    "reception_notice": 1,
    "reception_notice_return": -1,
    "reception_in_progress": 1,
    "reception_in_progress_return": -1,
    "delivery": -1,
    "delivery_return": 1,
    "delivery_notice": -1,
    "delivery_notice_return": 1,
    "plus_inventory": 1,
    "minus_inventory": -1,
    "consumption": -1,
    "consumption_return": 1,
    "usage_giving": -1,
    "usage_giving_return": 1,
    "production": 1,
    "production_return": -1,
    "dropshipped": -1,
    "dropshipped_return": 1,
}

# The internal moves are deliberately absent from the table above, and the
# report leaves them out of both sides of the comparison.
#
# Their sign on `l10n_ro_account_id` is not a constant: it flips with
# `product.category.l10n_ro_stock_account_change`.  With the flag off,
# `_get_product_accounts()` puts the product account under `stock_valuation`,
# which the entry credits, and `_compute_account` leaves `l10n_ro_account_id`
# on that same account - so the effect is negative.  With the flag on,
# `stock_valuation` becomes the source location account while
# `l10n_ro_account_id` follows the destination, which the entry debits - so the
# effect is positive, and the source lands on `l10n_ro_transfer_account_id`.
#
# Leaving them out costs nothing: an internal move takes its value and its
# journal entry from the same place, in the same step, so the two sides of this
# check cannot drift apart for it.  A missing entry on an internal move is a
# different defect, and one this report was never the tool for.
INTERNAL_MOVE_TYPES = (
    "internal_transfer",
    "internal_transit_out",
    "internal_transit_in",
)


class StockMove(models.Model):
    _inherit = "stock.move"

    # Up to 18.0 this field lived on stock.valuation.layer, which no longer
    # exists in 19.0; the valuation is carried by the stock move itself.
    rounding_adjustment = fields.Char()

    def correction_valuation_type(self):
        """Recompute the Romanian move type of the selected moves.

        Replaces the 18.0 `stock.valuation.layer.correction_valuation_type()`,
        which forced `l10n_ro_valued_type` on the layer; in 19.0 the equivalent
        is `stock.move.l10n_ro_move_type`, a stored computed field.
        """
        self._compute_l10n_ro_move_type()
        self.flush_recordset(["l10n_ro_move_type"])

    def correction_valuation(self, unlink_account_move=True, recompute_value=True):
        """Rebuild the valuation and the accounting entry of the moves.

        `recompute_value=False` keeps the value the move already carries -
        needed when it was forced through `value_manual`, which core would
        otherwise overwrite from the cost on an outgoing move.
        """
        if unlink_account_move:
            # In 19.0 `_create_account_move()` posts ONE entry for a whole
            # recordset and links every move to it, so dropping the entry of one
            # move also drops the lines of its siblings.  Up to 18.0 each
            # valuation layer had its own entry and the question did not arise.
            # Pull in every move sharing an entry with the selection, otherwise
            # correcting one line of a transfer silently leaves the other
            # products of that transfer with no entry at all.
            shared = self.env["stock.move"].search([("account_move_id", "in", self.account_move_id.ids)])
            self |= shared

        for move in self:
            if recompute_value and move._is_out():
                # Revalue the outgoing move at the current cost, the way
                # `_prepare_out_svl_vals` was used on the layer in 18.0.
                move._set_value()

            account_moves = move.account_move_id
            if "l10n_ro_extra_account_move_ids" in move._fields:
                account_moves |= move.l10n_ro_extra_account_move_ids

            if not unlink_account_move:
                value = abs(move.value)
                for line in account_moves.line_ids:
                    if line.debit:
                        line.with_context(check_move_validity=False).write({"debit": value})
                    else:
                        line.with_context(check_move_validity=False).write({"credit": value})
                continue

            name = move.account_move_id.name
            if account_moves:
                account_moves.write({"state": "draft"})
                account_moves.with_context(force_delete=True).unlink()
            move = move.with_context(force_period_date=move.date)
            move._create_account_move()
            if "l10n_ro_extra_account_move_ids" in move._fields:
                move._create_account_move_ro_extra()
            if name and move.account_move_id:
                move.account_move_id.write({"name": name})
